### ISSUE TITLE
[Improvement] for ModSci ontology

### ISSUE THREAD

**Issue by Hebaallahibrahim** [saidfathalla/Science-knowledge-graph-ontologies#1]
**Is your feature request related to a problem? Please describe.**
no. 
For ModSci ontology:
I'd suggest integrating several existing taxonomies of research fields, such as Field of Research (FoR) by ANZSRC and Dewey Decimal Classification scheme.

**Comment by Hebaallahibrahim** [comment]
can you provide an N-Triples serialization?

**Comment by saidfathalla** [comment]
> can you provide an N-Triples serialization?

thanks for your suggestion. N-Triples serialization has been generated.

**Comment by saidfathalla** [comment]
> **Is your feature request related to a problem? Please describe.**
> no.
> For ModSci ontology:
> I'd suggest integrating several existing taxonomies of research fields, such as Field of Research (FoR) by ANZSRC and Dewey Decimal Classification scheme.

Thanks for your suggestion, we are in the process of integrating  FoR and DDC.
