### ISSUE TITLE
Integration with existing taxonomy

### ISSUE THREAD

**Issue by s979** [saidfathalla/Science-knowledge-graph-ontologies#4]
It is an interesting work, I suggest to integrate your ontology with library of congress classification scheme.
(https://www.loc.gov/catdir/cpso/lcc.html#:~:text=The%20Library%20of%20Congress%20Classification,of%20the%20Library%20of%20Congress. )

**Comment by saidfathalla** [comment]
we will take this into consideration. Thanks for your suggestion.
