### ISSUE TITLE
[Improvement] Generalize class hierarchy description

### ISSUE THREAD

**Issue by dgarijo** [saidfathalla/Science-knowledge-graph-ontologies#5]
Hi @saidfathalla,

Someone referred me to the hierarchy visualization you have created in https://github.com/saidfathalla/Science-knowledge-graph-ontologies/blob/master/doc/ModSci_doc/Visualization/InteractiveVisualization.html and I think it looks really nice.

I have 2 questions: 

1) Do you think it would be useful to add it to Widoco, so others can use it too? Or is this visualization specific for this ontology?

2) Have you used a tool to transform your ontology data into the JSON needed by the D3 library? If so, do you mind sharing it?

Finally, I see the license in the page is CC-BY, but I don't know very well how to credit it. Can you please specify? Thanks in advance

**Comment by saidfathalla** [comment]
RE 1. yes, sure it will be really useful. No, it can be used for visualizing any class hierarchy.
RE 2. yes, we are still working on some improvements in that tool and we also writing a paper describing it. I will share it with you once ready.
Actually, ModSci is an ontology belonging to SKGO suite, which you can cite it via "Fathalla, Said, Sören Auer, and Christoph Lange. "Towards the semantic formalization of science." Proceedings of the 35th Annual ACM Symposium on Applied Computing. 2020." however, the paper for ModSci is currently under peer review at ISWC.

**Comment by saidfathalla** [comment]
You can find SKGO paper at https://dl.acm.org/doi/pdf/10.1145/3341105.3374132
